/**
 * Create actual files from the list which were generated by `Dumping tags for reporting bugs` on TagFolder.
 * This script reads tags from a file and creates markdown files in a structured directory format.
 * 
 * @version 1.0.0
 * @author vorotamoroz
 * @license Apache-2.0
 */

/**
 * Copyright 2025 vorotamoroz

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
**/

const w = await Deno.readTextFile("./tags.txt");
const out = `./out/dump-${Date.now()}`;
await Deno.mkdir(out, { recursive: true });
const lines = w.split("\n");
const dirSet = new Set<string>();

for (const i in lines) {
  const dirName = `000${~~(Number(i) / 1000)}`.slice(-3);
  const filename = `000000${i}`.slice(-5);
  const outDir = out + "/" + dirName;
  if (!dirSet.has(outDir)) {
    await Deno.mkdir(outDir, { recursive: true });
    dirSet.add(outDir);
  }

  const line = lines[i];
  // console.log(`${filename} -> ${line}`);
  await Deno.writeTextFile(outDir + "/" + filename + ".md", line);
}